import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Invoice from './Components/InVoice/Invoice'
import 'bootstrap/dist/css/bootstrap.min.css';
import Multivendors from './Multivendors/Multivendors'
import FAQ from './Components/FAQ/FAQ'
import Feedback from './Components/Feedback/Feedback'
import Contact from './Components/Contact/Contact'
import Blogs from './Components/Blogs/Blogs'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
     <Invoice></Invoice>
     <Multivendors></Multivendors>
     <FAQ></FAQ>
     <Feedback></Feedback>
     <Contact></Contact>
     <Blogs></Blogs>
      </main>
    </>
  )
}
